2024-01-10 22:13:00,301 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-10 23:32:07,618 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-10 23:32:09,992 django.request WARNING  Not Found: /favicon.ico
2024-01-12 00:38:20,573 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-12 00:40:15,939 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-12 00:41:58,218 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-12 00:48:20,990 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-12 00:49:36,496 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-12 00:51:29,970 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\PhotoCraft\settings\django.py changed, reloading.
2024-01-12 00:51:30,461 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-12 00:51:32,551 django.request WARNING  Not Found: /
2024-01-12 00:51:32,649 django.request WARNING  Not Found: /favicon.ico
2024-01-12 00:51:42,914 django.request WARNING  Not Found: /core_api/
2024-01-12 00:52:00,777 django.request WARNING  Not Found: /core_api/photos/
2024-01-12 00:52:11,830 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\urls.py changed, reloading.
2024-01-12 00:52:12,314 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-12 00:52:13,411 django.request ERROR    Internal Server Error: /core_api/photos/
Traceback (most recent call last):
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\photo_list_view\view.py", line 20, in get
    return Response({'pagination': CustomPagination(outcome.process(), current_page=outcome.celaned_data['page'],
                                                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PhotoListService' object has no attribute 'celaned_data'
2024-01-12 00:52:14,602 django.request ERROR    Internal Server Error: /core_api/photos/
Traceback (most recent call last):
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\photo_list_view\view.py", line 20, in get
    return Response({'pagination': CustomPagination(outcome.process(), current_page=outcome.celaned_data['page'],
                                                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PhotoListService' object has no attribute 'celaned_data'
2024-01-12 00:52:31,050 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\photo_list_view\view.py changed, reloading.
2024-01-12 00:52:31,582 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-13 17:59:19,892 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-13 18:03:21,940 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-13 18:15:28,391 django.request WARNING  Not Found: /
2024-01-13 18:15:28,454 django.request WARNING  Not Found: /favicon.ico
2024-01-13 18:15:46,571 django.request WARNING  Not Found: /core_api/
2024-01-13 20:28:39,233 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-13 21:28:42,679 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-13 21:29:01,787 django.request WARNING  Not Found: /
2024-01-13 21:29:01,800 django.request WARNING  Not Found: /
2024-01-13 21:29:01,873 django.request WARNING  Not Found: /favicon.ico
2024-01-14 00:19:20,747 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 00:19:37,483 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 00:19:38,190 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 00:19:40,794 django.request WARNING  Not Found: /
2024-01-14 00:19:44,722 django.request WARNING  Not Found: /
2024-01-14 00:19:45,604 django.request WARNING  Not Found: /
2024-01-14 00:19:46,622 django.request WARNING  Not Found: /
2024-01-14 00:19:58,988 django.request WARNING  Not Found: /core_api/
2024-01-14 00:20:10,984 django.request ERROR    Internal Server Error: /core_api/categories/
Traceback (most recent call last):
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CategoryView.get() takes 1 positional argument but 2 were given
2024-01-14 00:23:00,378 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 00:23:01,055 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 00:23:05,088 django.request ERROR    Internal Server Error: /core_api/categories/
Traceback (most recent call last):
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py", line 19, in get
    return Response(CategorySerializer(outcome.process().object_list, many=True).data)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'object_list'
2024-01-14 00:23:07,457 django.request ERROR    Internal Server Error: /core_api/categories/
Traceback (most recent call last):
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-FQlYvGh1\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py", line 19, in get
    return Response(CategorySerializer(outcome.process().object_list, many=True).data)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'object_list'
2024-01-14 00:26:05,759 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 00:26:06,441 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 00:33:53,994 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\services\create_category_service\service.py changed, reloading.
2024-01-14 00:33:54,702 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 00:39:38,724 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 01:52:10,303 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 01:52:33,777 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:07:43,012 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:07:44,713 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:07:49,700 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:07:52,192 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:07:53,127 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:07:53,884 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:07:54,529 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:04,478 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:05,347 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:05,782 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:06,001 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:06,214 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:09,320 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\permissions.py changed, reloading.
2024-01-14 02:08:10,612 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:08:32,351 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\permissions.py changed, reloading.
2024-01-14 02:08:33,873 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:08:34,621 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:37,232 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:38,239 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:08:39,355 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:13:43,817 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:13:45,220 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:15:45,940 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:15:47,518 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:16:03,132 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:16:04,686 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:16:09,314 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:16:10,950 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:16:18,162 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:16:19,528 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:16:31,351 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:16:32,764 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:16:50,150 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:16:51,695 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:16:52,677 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:16:54,826 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:16:55,723 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:16:56,490 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:16:57,302 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:16:58,636 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:17:09,193 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:17:10,694 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:17:30,833 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:17:32,237 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:17:32,978 django.request WARNING  Unauthorized: /core_api/categories/
2024-01-14 02:17:41,724 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:17:43,417 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:22:55,669 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:22:57,282 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:23:44,461 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:23:45,903 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 02:25:23,305 django.utils.autoreload INFO     D:\PhotoCraft\PhotoCraft\PhotoCraft\core_api\veiws\category_view\view.py changed, reloading.
2024-01-14 02:25:24,810 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 22:56:00,780 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 22:57:54,697 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\categories_view\view.py changed, reloading.
2024-01-14 22:57:55,128 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 22:57:56,426 django.request WARNING  Not Found: /
2024-01-14 22:57:56,540 django.request WARNING  Not Found: /favicon.ico
2024-01-14 22:58:07,472 django.request WARNING  Not Found: /coer_api/
2024-01-14 22:58:15,748 django.request WARNING  Not Found: /core_api/
2024-01-14 22:58:35,600 django.request WARNING  Not Found: /core_api/catgeries/
2024-01-14 22:58:45,247 django.request WARNING  Not Found: /core_api/categries/
2024-01-14 23:00:18,026 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\categories_view\view.py changed, reloading.
2024-01-14 23:00:18,472 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 23:14:19,432 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\urls.py changed, reloading.
2024-01-14 23:14:19,883 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-14 23:14:27,480 django.request WARNING  Not Found: /core_api/
2024-01-14 23:14:37,595 django.request ERROR    Internal Server Error: /core_api/photo/1
Traceback (most recent call last):
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\photo_view\view.py", line 19, in get
    return Response(PhotoService(outcome.process()).data)
                                 ^^^^^^^^^^^^^^^^^
  File "D:\Projects\PhotoCraft\PhotoCraft\core_api\services\photo_service\service.py", line 13, in process
    return Photo.objects.get(id=self.cleaned_data['id'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmstv\.virtualenvs\PhotoCraft-YY6TIEDM\Lib\site-packages\django\db\models\query.py", line 647, in get
    raise self.model.DoesNotExist(
models_app.models.Photo.model.Photo.DoesNotExist: Photo matching query does not exist.
2024-01-15 02:17:54,495 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\photo_view\view.py changed, reloading.
2024-01-15 02:17:54,914 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-16 00:51:20,556 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-16 00:51:23,554 django.request WARNING  Not Found: /
2024-01-16 00:51:23,684 django.request WARNING  Not Found: /favicon.ico
2024-01-16 00:52:47,108 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\categories_view\view.py changed, reloading.
2024-01-16 00:52:47,665 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 16:08:00,093 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 16:30:02,928 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 16:35:53,491 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\photo_craft\settings\database.py changed, reloading.
2024-01-19 16:35:53,922 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 16:35:58,833 django.request WARNING  Not Found: /
2024-01-19 16:35:58,865 django.request WARNING  Not Found: /favicon.ico
2024-01-19 20:34:11,360 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 20:37:22,713 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\__init__.py changed, reloading.
2024-01-19 20:37:23,166 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 20:38:28,870 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\photo\photo_list\view.py changed, reloading.
2024-01-19 20:38:29,289 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 20:38:42,729 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\core_api\veiws\photo\photo\view.py changed, reloading.
2024-01-19 20:38:43,147 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 20:38:45,131 django.request WARNING  Not Found: /
2024-01-19 20:38:45,246 django.request WARNING  Not Found: /favicon.ico
2024-01-19 20:50:05,188 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\comments\model.py changed, reloading.
2024-01-19 20:50:05,617 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 20:55:06,579 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\liked\model.py changed, reloading.
2024-01-19 20:55:07,011 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 21:01:05,040 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\photo\model.py changed, reloading.
2024-01-19 21:01:05,454 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 21:04:26,924 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\photo\model.py changed, reloading.
2024-01-19 21:04:27,354 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 21:27:51,457 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\photo\model.py changed, reloading.
2024-01-19 21:27:51,964 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 21:29:45,672 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\photo\model.py changed, reloading.
2024-01-19 21:29:46,106 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 21:50:18,160 django.utils.autoreload INFO     D:\Projects\PhotoCraft\PhotoCraft\models_app\models\photo\model.py changed, reloading.
2024-01-19 21:50:18,609 django.utils.autoreload INFO     Watching for file changes with StatReloader
2024-01-19 23:10:03,757 django.utils.autoreload INFO     Watching for file changes with StatReloader
